-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 02:32:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema practica_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema practica_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practica_web` DEFAULT CHARACTER SET utf8 ;
USE `practica_web` ;

-- -----------------------------------------------------
-- Table `practica_web`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_web`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `registro_academico` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(120) NOT NULL,
  `contrasena` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `registro_academico_UNIQUE` (`registro_academico` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_web`.`catedraticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_web`.`catedraticos` (
  `id_catedraticos` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_catedraticos`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_web`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_web`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(80) NOT NULL,
  `creditos` INT NOT NULL DEFAULT 5,
  `area` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_web`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_web`.`publicacion` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_curso` INT NULL,
  `id_catedratico` INT NULL,
  `mensaje` LONGTEXT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_curso_idx` (`id_curso` ASC) VISIBLE,
  INDEX `id_catedratico_idx` (`id_catedratico` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `practica_web`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `practica_web`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_catedratico`
    FOREIGN KEY (`id_catedratico`)
    REFERENCES `practica_web`.`catedraticos` (`id_catedraticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_web`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_web`.`comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_publicacion` INT NOT NULL,
  `id_usuario_com` INT NOT NULL,
  `mensaje` LONGTEXT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `id_publicacion_idx` (`id_publicacion` ASC) VISIBLE,
  INDEX `id_usuario_idx` (`id_usuario_com` ASC) VISIBLE,
  CONSTRAINT `id_publicacion`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `practica_web`.`publicacion` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario_com`
    FOREIGN KEY (`id_usuario_com`)
    REFERENCES `practica_web`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_web`.`curso_aprobado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica_web`.`curso_aprobado` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_curapro` INT NOT NULL,
  `id_curso_curapro` INT NOT NULL,
  `fecha_aprobacion` DATE NOT NULL,
  PRIMARY KEY (`id_registro`),
  INDEX `id_usuario_idx` (`id_usuario_curapro` ASC) VISIBLE,
  INDEX `id_curso_idx` (`id_curso_curapro` ASC) VISIBLE,
  CONSTRAINT `id_usuario_curapro`
    FOREIGN KEY (`id_usuario_curapro`)
    REFERENCES `practica_web`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_curso_curapro`
    FOREIGN KEY (`id_curso_curapro`)
    REFERENCES `practica_web`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
